# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
   name: Proses Perakitan Kernel
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
      - uses: actions/checkout@v4
      
      - name: Build Kernel
      - uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/jedld/kernel_samsung_gtexsle
          kernel-branch: master
          config: gtexslte_defconfig
          arch: arm
          aosp-gcc: true
          aosp-clang: true
        
          android-version: 7.1
          aosp-clang-version: r383902
          
          anykernel3: true
          nethunter: true
          nethunter-patch: true
          
          release: true
         access-token: ${{  secrets.GITHUB_TOKEN  }}
